### ISSUE TITLE
Add serial numbers to SE Global Flag Summary

### ISSUE THREAD

**Issue by double-fault** [Floern/stackoverflow#2]
It would be useful to add Serial Numbers in a different column in the Userscirpt. Something like a thin column to the left of the "sites".

**Comment by Floern** [comment]
What exactly do you mean by serial number? A simple enumeration (ranking) of the sites?

**Comment by double-fault** [comment]
@Floern I mean like besides the sites, put like for the first site, "1", for the second one in the column put "2" etc.
