### ISSUE TITLE
No longer displaying sites

### ISSUE THREAD

**Issue by BasicNullification** [Floern/stackoverflow#7]
I've been using this userscript relatively frequently so I can say this issue just arose this morning.

Upon navigating to `//stackexchange.com/users/#####/?tab=flags`, the site number increases, but it no longer displays the actual site, as shown in the below image.

[![enter image description here][1]][1]

Even upon allowing it to finish, the list of sites never show up.

  [1]: https://i.stack.imgur.com/uyS01.png

**Comment by Floern** [comment]
Working on it... SE changed the flag summary layout, so the script doesn't find the flag count anymore.

**Comment by Floern** [comment]
Fixed in [1.2.1](https://github.com/Floern/stackoverflow/blob/master/userscripts/SE_global_flag_summary.user.js?raw=true).
